name: deploy site

on:
  push:
   tags:
    - 'doc*'
jobs:
  main:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repo
      uses: actions/checkout@v2 
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.1.3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install
      run: pnpm install
    - name: build
      run: pnpm run docs:build
    - name: deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "docs/.vitepress/dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/node_modules/"